### ISSUE TITLE
Token de acceso al WNS

### ISSUE THREAD

**Issue by juanpsenn** [WhyNotHugo/django-afip#29]
> El CEE ya posee un TA valido para el acceso al WSN solicitado

Is there any way to take control of the request for a new token? I don't know why this happen from time to time.
I found that this error appears when you are trying to get a new token when there is an other valid token. How can i get that valid token and used it intead of asking for a new one?

**Comment by WhyNotHugo** [comment]
The app tries to use the latest token (unless there isn't one, or it's expired).

If you're getting this error, it can mean one of two things:
1. You have two (or more) processes running in parallel, and one fetched a token _after_ another process fetched it, but _before_ it was committed into the DB (this can happen if you have high concurrency).
1. The token was fetched by some other application. I've seen this issue, for example, in CI, when one run got a token, and the next run tries to get a token (CI runs in a clear environment, so the previous one gets lost). The timeout is a few minutes. Live-testing when clearing the database can be a PITA because of this.

**Comment by juanpsenn** [comment]
Thanks you, i'll check my processes then! Closing issue.

**Comment by WhyNotHugo** [comment]
Sure! If you the issue is lots of concurrent attempts at once, I suggest you use a single task runner for invoice validation and alike.

Let me know if this does end up looking like a bug elsewhere.
